Parameters:
  path_to_features: /Users/nathanael/Documents/Concrete/Projetos/Cartao_Branco/odete-tests/specs/cartaobranco/functional_testing/features/
  platforms: android, ios
  report_name: Cartão Branco-Sprint-01
  ios_unit_test_report: /Users/nathanael/Documents/report/index-2.html
  jira_android: true  
  jira_ios: true 
  